index:
    path: /
    controller: App\Controller\DefaultController::index

app_lucky_number:
  path: /lucky/number
  controller: App\Controller\LuckyController::number

app_distance_calculator:
  path: /distance/calculate
  controller: App\Controller\DistanceController::calculate